name: gn_accessor
description: A new Flutter project.
version: 0.1.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_form_builder: ^7.7.0
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true