name: gn_accessor
description: A new Flutter project.
version: 0.1.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.2.1
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  flutter_form_builder: ^7.7.0
  provider: ^6.0.4
  intl: ^0.17.0
  circular_menu: ^2.0.1
  battery_info: ^1.1.1
  flutter_smart_dialog: ^4.6.1+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-VariableFont_wght.ttf
        - asset: assets/fonts/JetBrainsMono-Italic-VariableFont_wght.ttf