name: gn_accessor
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_form_builder: ^7.1.1
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/general/
    - assets/home/

  fonts:
    - family: PoorStory
      fonts:
        - asset: assets/fonts/PoorStory-Regular.ttf